// Testing pathfinding responses when pathways are interrupted by other entities
function EntityMovementPlanner_interruptedMovementTest()
{
    const gameMap = new GameMap(24, 24);
    gameMap.fill(0, 0, gameMap.width, gameMap.height, "wall");
    gameMap.fill(10, 10, gameMap.width - 10, gameMap.height - 10, "floor");
    gameMap.line(10, 4, 10, 9, { cellType: "floor" });
    gameMap.line(8, 8, 12, 8, { cellType: "floor" });
    gameMap.line(8, 6, 12, 6, { cellType: "floor" });
    gameMap.line(13, 14, 13, 19, { cellType: "floor" });
    gameMap.line(11, 15, 15, 15, { cellType: "floor" });
    gameMap.line(11, 17, 15, 17, { cellType: "floor" });

    const width = gameMap.width;
    const height = gameMap.height;

    gameMap.addEntity(BuildMapEntityLemming(10, 10, 1));
    gameMap.entities[0].setPatrolPoints(
        gameMap,
        [
            { x: width - 11, y: 10 },
            { x: 10, y: 10 },
        ]
    );

    gameMap.addEntity(BuildMapEntityLemming(width - 11, 10, 2));
    gameMap.entities[1].setPatrolPoints(
        gameMap,
        [
            { x: width - 11, y: height - 11 },
            { x: width - 11, y: 10 },
        ]
    );

    gameMap.addEntity(BuildMapEntityLemming(width - 11, height - 11, 3));
    gameMap.entities[2].setPatrolPoints(
        gameMap,
        [
            { x: 10, y: height - 11 },
            { x: width - 11, y: height - 11 },
        ]
    );

    gameMap.addEntity(BuildMapEntityLemming(10, height - 11, 0));
    gameMap.entities[3].setPatrolPoints(
        gameMap,
        [
            { x: 10, y: 10 },
            { x: 10, y: height - 11 },
        ]
    );

    gameMap.addEntity(BuildMapEntityLemming(8, 6, 1));
    gameMap.entities[4].setPatrolPoints(
        gameMap,
        [
            { x: 8, y: 6 },
            { x: 12, y: 6 },
        ]
    );

    gameMap.addEntity(BuildMapEntityLemming(12, 8, 3));
    gameMap.entities[5].setPatrolPoints(
        gameMap,
        [
            { x: 8, y: 8 },
            { x: 12, y: 8 },
        ]
    );

    gameMap.addEntity(BuildMapEntityLemming(11, 15, 1));
    gameMap.entities[6].setPatrolPoints(
        gameMap,
        [
            { x: 15, y: 15 },
            { x: 11, y: 15 },
        ]
    );

    gameMap.addEntity(BuildMapEntityLemming(15, 17, 3));
    gameMap.entities[7].setPatrolPoints(
        gameMap,
        [
            { x: 11, y: 17 },
            { x: 15, y: 17 },
        ]
    );

    gameMap.addEntity(BuildMapEntityLemming(10, 4, 2));
    gameMap.entities[8].setPatrolPoints(
        gameMap,
        [
            { x: 13, y: 19 },
            { x: 10, y: 4 },
        ]
    );

    gameMap.addEntity(BuildMapEntityLemming(13, 19, 0));
    gameMap.entities[9].setPatrolPoints(
        gameMap,
        [
            { x: 10, y: 4 },
            { x: 13, y: 19 },
        ]
    );

    const movements = [];
    movements.push(gameMap.entities.map(e => ({
        id: e.id,
        x: e.x,
        y: e.y,
        direction: e.direction,
        displayCharacter: e.id < 9
            ? undefined
            : ["⬆️", "➡️", "⬇️", "⬅️"][e.direction % 4]
    })));

    for (let i = 0; i < 64; i++) {
        gameMap.moveEntities();
        movements.push(gameMap.entities.map(e => ({
            id: e.id,
            x: e.x,
            y: e.y,
            direction: e.direction,
            displayCharacter: e.id < 9
                ? undefined
                : ["⬆️", "➡️", "⬇️", "⬅️"][e.direction % 4]
        })));
    }

    test(
        "Interrupted Movement Test",
        () => {
            /**
             * Note that we're only testing the positions since the directions
             * can be randomized if the target is behind the entity. In those
             * cases, the entitiy will choose either left or right. These can
             * be omitted from the test since the positions over time are enough
             * to validate that the movement is taking place without collisions
             */
            const expectedPositions = [
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 10, y:  4 },
                    { id: 10, x: 13, y: 19 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x:  9, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 14, y: 17 },
                    { id:  9, x: 10, y:  5 },
                    { id: 10, x: 13, y: 18 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x: 10, y:  6 },
                    { id:  6, x: 10, y:  8 },
                    { id:  7, x: 13, y: 15 },
                    { id:  8, x: 13, y: 17 },
                    { id:  9, x: 10, y:  5 },
                    { id: 10, x: 13, y: 18 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x: 11, y:  6 },
                    { id:  6, x:  9, y:  8 },
                    { id:  7, x: 14, y: 15 },
                    { id:  8, x: 12, y: 17 },
                    { id:  9, x: 10, y:  6 },
                    { id: 10, x: 13, y: 17 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 10, y:  7 },
                    { id: 10, x: 13, y: 16 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 10, y:  8 },
                    { id: 10, x: 13, y: 15 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 10, y:  9 },
                    { id: 10, x: 13, y: 14 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x: 11, y:  6 },
                    { id:  6, x:  9, y:  8 },
                    { id:  7, x: 14, y: 15 },
                    { id:  8, x: 12, y: 17 },
                    { id:  9, x: 10, y: 10 },
                    { id: 10, x: 13, y: 13 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 10, y:  6 },
                    { id:  6, x: 10, y:  8 },
                    { id:  7, x: 13, y: 15 },
                    { id:  8, x: 13, y: 17 },
                    { id:  9, x: 10, y: 11 },
                    { id: 10, x: 13, y: 12 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x:  9, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 14, y: 17 },
                    { id:  9, x: 10, y: 11 },
                    { id: 10, x: 13, y: 12 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 11, y: 11 },
                    { id: 10, x: 12, y: 12 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 12, y: 11 },
                    { id: 10, x: 11, y: 12 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 13, y: 11 },
                    { id: 10, x: 10, y: 12 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x:  9, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 14, y: 17 },
                    { id:  9, x: 13, y: 11 },
                    { id: 10, x: 10, y: 12 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x: 10, y:  6 },
                    { id:  6, x: 10, y:  8 },
                    { id:  7, x: 13, y: 15 },
                    { id:  8, x: 13, y: 17 },
                    { id:  9, x: 13, y: 11 },
                    { id: 10, x: 10, y: 12 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x: 11, y:  6 },
                    { id:  6, x:  9, y:  8 },
                    { id:  7, x: 14, y: 15 },
                    { id:  8, x: 12, y: 17 },
                    { id:  9, x: 12, y: 11 },
                    { id: 10, x: 11, y: 12 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 12, y: 11 },
                    { id: 10, x: 11, y: 12 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 12, y: 12 },
                    { id: 10, x: 11, y: 11 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 12, y: 12 },
                    { id: 10, x: 11, y: 11 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 11, y:  6 },
                    { id:  6, x:  9, y:  8 },
                    { id:  7, x: 14, y: 15 },
                    { id:  8, x: 12, y: 17 },
                    { id:  9, x: 13, y: 12 },
                    { id: 10, x: 10, y: 11 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 10, y:  6 },
                    { id:  6, x: 10, y:  8 },
                    { id:  7, x: 13, y: 15 },
                    { id:  8, x: 13, y: 17 },
                    { id:  9, x: 13, y: 12 },
                    { id: 10, x: 10, y: 11 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x:  9, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 14, y: 17 },
                    { id:  9, x: 13, y: 12 },
                    { id: 10, x: 10, y: 11 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 13, y: 12 },
                    { id: 10, x: 10, y: 11 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 13, y: 13 },
                    { id: 10, x: 10, y: 10 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 13, y: 14 },
                    { id: 10, x: 10, y:  9 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x:  9, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 14, y: 17 },
                    { id:  9, x: 13, y: 15 },
                    { id: 10, x: 10, y:  8 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x: 10, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 13, y: 17 },
                    { id:  9, x: 13, y: 16 },
                    { id: 10, x: 10, y:  7 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x: 11, y:  6 },
                    { id:  6, x: 10, y:  8 },
                    { id:  7, x: 13, y: 15 },
                    { id:  8, x: 12, y: 17 },
                    { id:  9, x: 13, y: 17 },
                    { id: 10, x: 10, y:  6 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  9, y:  8 },
                    { id:  7, x: 14, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 13, y: 18 },
                    { id: 10, x: 10, y:  5 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 13, y: 19 },
                    { id: 10, x: 10, y:  4 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 13, y: 19 },
                    { id: 10, x: 10, y:  4 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 11, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 12, y: 17 },
                    { id:  9, x: 13, y: 19 },
                    { id: 10, x: 10, y:  4 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 10, y:  6 },
                    { id:  6, x:  9, y:  8 },
                    { id:  7, x: 14, y: 15 },
                    { id:  8, x: 13, y: 17 },
                    { id:  9, x: 13, y: 18 },
                    { id: 10, x: 10, y:  5 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x:  9, y:  6 },
                    { id:  6, x: 10, y:  8 },
                    { id:  7, x: 13, y: 15 },
                    { id:  8, x: 14, y: 17 },
                    { id:  9, x: 13, y: 17 },
                    { id: 10, x: 10, y:  6 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 13, y: 16 },
                    { id: 10, x: 10, y:  7 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 13, y: 15 },
                    { id: 10, x: 10, y:  8 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 13, y: 14 },
                    { id: 10, x: 10, y:  9 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x:  9, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 14, y: 17 },
                    { id:  9, x: 13, y: 14 },
                    { id: 10, x: 10, y:  9 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x: 10, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 13, y: 17 },
                    { id:  9, x: 13, y: 13 },
                    { id: 10, x: 10, y: 10 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x: 11, y:  6 },
                    { id:  6, x: 10, y:  8 },
                    { id:  7, x: 13, y: 15 },
                    { id:  8, x: 12, y: 17 },
                    { id:  9, x: 13, y: 13 },
                    { id: 10, x: 10, y: 10 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  9, y:  8 },
                    { id:  7, x: 14, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 13, y: 12 },
                    { id: 10, x: 10, y: 11 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 13, y: 12 },
                    { id: 10, x: 10, y: 11 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 12, y: 12 },
                    { id: 10, x: 11, y: 11 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x: 11, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 12, y: 17 },
                    { id:  9, x: 11, y: 12 },
                    { id: 10, x: 12, y: 11 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x: 10, y:  6 },
                    { id:  6, x:  9, y:  8 },
                    { id:  7, x: 14, y: 15 },
                    { id:  8, x: 13, y: 17 },
                    { id:  9, x: 10, y: 12 },
                    { id: 10, x: 13, y: 11 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x:  9, y:  6 },
                    { id:  6, x: 10, y:  8 },
                    { id:  7, x: 13, y: 15 },
                    { id:  8, x: 14, y: 17 },
                    { id:  9, x: 10, y: 12 },
                    { id: 10, x: 13, y: 11 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 10, y: 12 },
                    { id: 10, x: 13, y: 11 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 11, y: 12 },
                    { id: 10, x: 12, y: 11 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 11, y: 12 },
                    { id: 10, x: 12, y: 11 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x:  9, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 14, y: 17 },
                    { id:  9, x: 11, y: 11 },
                    { id: 10, x: 12, y: 12 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 10, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 13, y: 17 },
                    { id:  9, x: 11, y: 11 },
                    { id: 10, x: 12, y: 12 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 11, y:  6 },
                    { id:  6, x: 10, y:  8 },
                    { id:  7, x: 13, y: 15 },
                    { id:  8, x: 12, y: 17 },
                    { id:  9, x: 10, y: 11 },
                    { id: 10, x: 13, y: 12 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  9, y:  8 },
                    { id:  7, x: 14, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 10, y: 11 },
                    { id: 10, x: 13, y: 12 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 10, y: 11 },
                    { id: 10, x: 13, y: 12 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 10, y: 11 },
                    { id: 10, x: 13, y: 12 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x: 11, y:  6 },
                    { id:  6, x:  8, y:  8 },
                    { id:  7, x: 15, y: 15 },
                    { id:  8, x: 12, y: 17 },
                    { id:  9, x: 10, y: 10 },
                    { id: 10, x: 13, y: 13 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x: 10, y:  6 },
                    { id:  6, x:  9, y:  8 },
                    { id:  7, x: 14, y: 15 },
                    { id:  8, x: 13, y: 17 },
                    { id:  9, x: 10, y:  9 },
                    { id: 10, x: 13, y: 14 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x:  9, y:  6 },
                    { id:  6, x: 10, y:  8 },
                    { id:  7, x: 13, y: 15 },
                    { id:  8, x: 14, y: 17 },
                    { id:  9, x: 10, y:  9 },
                    { id: 10, x: 13, y: 14 },
                ],
                [
                    { id:  1, x: 13, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 10, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 10, y:  8 },
                    { id: 10, x: 13, y: 15 },
                ],
                [
                    { id:  1, x: 12, y: 10 },
                    { id:  2, x: 13, y: 13 },
                    { id:  3, x: 11, y: 13 },
                    { id:  4, x: 10, y: 10 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 10, y:  7 },
                    { id: 10, x: 13, y: 16 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 12 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 11 },
                    { id:  5, x:  8, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 15, y: 17 },
                    { id:  9, x: 10, y:  6 },
                    { id: 10, x: 13, y: 17 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 11 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 12 },
                    { id:  5, x:  9, y:  6 },
                    { id:  6, x: 12, y:  8 },
                    { id:  7, x: 11, y: 15 },
                    { id:  8, x: 14, y: 17 },
                    { id:  9, x: 10, y:  5 },
                    { id: 10, x: 13, y: 18 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 10, y:  6 },
                    { id:  6, x: 11, y:  8 },
                    { id:  7, x: 12, y: 15 },
                    { id:  8, x: 13, y: 17 },
                    { id:  9, x: 10, y:  4 },
                    { id: 10, x: 13, y: 19 },
                ],
                [
                    { id:  1, x: 10, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 13, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 11, y:  6 },
                    { id:  6, x: 10, y:  8 },
                    { id:  7, x: 13, y: 15 },
                    { id:  8, x: 12, y: 17 },
                    { id:  9, x: 10, y:  4 },
                    { id: 10, x: 13, y: 19 },
                ],
                [
                    { id:  1, x: 11, y: 10 },
                    { id:  2, x: 13, y: 10 },
                    { id:  3, x: 12, y: 13 },
                    { id:  4, x: 10, y: 13 },
                    { id:  5, x: 12, y:  6 },
                    { id:  6, x:  9, y:  8 },
                    { id:  7, x: 14, y: 15 },
                    { id:  8, x: 11, y: 17 },
                    { id:  9, x: 10, y:  4 },
                    { id: 10, x: 13, y: 19 },
                ],
            ];

            const positions =
                movements.map(e => e.map(p => ({ id: p.id, x: p.x, y: p.y, })));

            Assert.deepEquals(expectedPositions, positions);
        },
        renderMovementContext(gameMap, movements)
    );
}
